# Generated by Django 3.2.6 on 2021-08-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_visitedlinks_visitedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitedlink',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
